   <div class="terms-condition text-aling-justify p-3 max-vh-md-50 min-vh-sm-50">
      <p style="line-height:normal;background:white;border:none;"><strong><span style="font-size:12px;color:#44546A;">Portal Educonexiones</span></strong></p>
      <p style="line-height:normal;background:white;border:none;"><strong><span style="font-size:12px;color:#44546A;">Términos y Condiciones.</span></strong></p>
      <p style="margin-left:35.4pt;text-indent:-35.4pt;line-height:normal;background:white;border:none;"><strong><span style="font-size:12px;color:#44546A;">Educonexiones</span></strong><span style="font-size:12px;color:#44546A;">, le da la bienvenida.</span></p>
      <p style="text-align:justify;line-height:normal;background:white;border:none;"><span style="font-size:12px;color:#44546A;">A continuación, presentamos los términos y condiciones que como usuario del portal <strong>Educonexioes</strong> <span style="background:yellow;">(<u>dirección web pendiente por incluir</u>)</span> debe conocer y aceptar para acceder a los servicios y contenidos que tiene vinculados. &nbsp;&nbsp;</span></p>
      <p style="text-align:justify;line-height:normal;background:white;border:none;"><strong><span style="font-size:12px;color:#44546A;">ANOTACIÓN:</span></strong><span style="font-size:12px;color:#44546A;">&nbsp;se entiende como usuario de <strong>Educonexiones,&nbsp;</strong> toda persona que ingrese a la dirección web (<span style="background:yellow;">pendiente por incluir</span>) y a las&nbsp;</span><span style="font-size:12px;color:#44546A;">páginas asociadas a esta</span>
         <a href="#_msocom_1" id="_anchor_1" language="JavaScript" name="_msoanchor_1">[1]</a> <span style="font-size:12px;color:#44546A;">&nbsp;url, para usar los servicios y contenidos que ofrece.&nbsp;</span></p>
      <p style="text-align:justify;line-height:normal;background:white;border:none;"><strong><span style="font-size:12px;color:#44546A;">IMPORTANTE</span></strong><span style="font-size:12px;color:#44546A;">: al aceptar los términos y condiciones que aquí se exponen, usted se reconoce como usuario de <strong>Educonexinoes</strong>, manifiesta comprender a cabalidad el sentido y alcance de los mismos, y manifiesta de manera expresa estar de acuerdo con estos.</span></p>
      <p style="text-align:justify;line-height:normal;background:white;border:none;"><strong><span style="font-size:12px;color:#44546A;">RECOMENDACIÓN</span></strong><span style="font-size:12px;color:#44546A;">: cada<strong>&nbsp;</strong>que ingrese a <strong>Educonexines</strong>, consulte de nuevo los términos y condiciones dispuesto en la plataforma, pues estos pueden ser modificados y actualizados en cualquier momento sin previo aviso.&nbsp;</span></p>
      <ol style="list-style-type: decimal;margin-left:0cmundefined;">
         <li><strong><span style="font-size:12px;color:#44546A;">Alcance del servicio y requerimientos técnicos&nbsp;</span></strong></li>
      </ol>
      <p style="text-align:justify;line-height:normal;background:white;border:none;"><strong><span style="font-size:12px;color:#44546A;">Educonexiones</span></strong><span style="font-size:12px;color:#44546A;">&nbsp;pone a disposición de los usuarios una serie de contenidos educativos en diferentes formatos (texto, audio, imagen, video) que requieren para su visualización y exploración de acceso a internet. Es responsabilidad de quien adquiere el servicio, contar con los equipos técnicos necesarios para acceder a los contenidos y garantizar que haya conectividad a Internet con las características óptimas para la visualización de estos. El usuario, en todo momento, es responsable de los costos que esto implica.&nbsp;</span></p>
      <ol style="list-style-type: undefined;margin-left:0cmundefined;">
         <li><strong><span style="font-size:12px;color:#44546A;">Administración del portal&nbsp;</span></strong></li>
      </ol>
      <p style="text-align:justify;line-height:normal;background:white;border:none;"><span style="font-size:12px;color:#44546A;">El diseño, arquitectura y contenidos que hacen parte del portal son propiedad de <strong>Estratégica Comunicaciones</strong>, de manera que todas las modificaciones en este (cambio de imagen, permisos de acceso, eliminación o inclusión de contenidos, entre otras posibles) quedan a discreción de la mencionada empresa y podrán ser realizadas de manera autónoma sin notificación alguna a los usuarios.&nbsp;</span></p>
      <ol style="list-style-type: undefined;margin-left:0cmundefined;">
         <li><strong><span style="font-size:12px;color:#44546A;">Acceso a contenidos&nbsp;</span></strong></li>
      </ol>
      <p style="text-align:justify;line-height:normal;background:white;border:none;"><span style="font-size:12px;color:#44546A;">Los contenidos descriptivos y demostrativos (prueba gratuita) del portal son de libre acceso, pero para hacer uso de las guías de aprendizaje (total o parcialmente) y los implementos de laboratorio, el usuario deberá realizar una suscripción y/o pago que está estipulado para cada servicio o producto, los cuales serán definidos por <strong>Estratégica Comunicaciones.&nbsp;</strong></span></p>
      <ol style="list-style-type: undefined;margin-left:0cmundefined;">
         <li><strong><span style="font-size:12px;color:#44546A;">Derechos de uso del portal</span></strong></li>
      </ol>
      <p style="text-align:justify;line-height:normal;background:white;border:none;"><span style="font-size:12px;color:#44546A;">Al aceptar estos términos y condiciones, el usuario de <strong>Educonexiones</strong> se compromete a que en el momento de acceder al portal, hará uso de los servicios que este ofrece de acuerdo a lo estipulado en las leyes de derechos de autor y uso de datos personales vigentes en Colombia, y en el país desde el cual ingrese. De acuerdo con lo establecido aquí, el usuario se abstiene de realizar en el portal actos con fines o efectos ilícitos, nocivos y clandestinos, que de cualquier forma puedan afectar el buen funcionamiento del portal y/o los servicios proporcionados por este. &nbsp;De igual manera, si el usuario conoce de intenciones o actos que podrían dañar el sistema, se compromete a notificar a<strong>&nbsp;Estratégica Comunicaciones</strong> y a denunciar ante las autoridades competentes. &nbsp;</span></p>
      <p style="text-align:justify;line-height:normal;background:white;border:none;"><span style="font-size:12px;color:#44546A;">En caso de identificar un intento de daño al portal, <strong>Estratégica Comunicaciones</strong> podrá suspender los servicios al usuario inmediatamente y solo se reestablecerá cuando se haya esclarecido la situación y demuestre que está exento de responsabilidad.&nbsp;</span></p>
      <p style="text-align:justify;line-height:normal;background:white;border:none;"><span style="font-size:12px;color:#44546A;">En todos los casos, el usuario se abstendrá de obtener, e incluso, intentar obtener, contenido o servicios del portal a través de medios o procedimientos distintos a los definidos por <strong>Estratégica Comunicaciones</strong>, razón por la que se obliga a acceder y hacer uso de estos de manera correcta y lícita. En caso contrario, <strong>Estratégica Comunicaciones&nbsp;</strong>podrá suspender el servicio, notificar las razones de esto y si es el caso, denunciar ante las entidades competentes para que se tomen las medidas de protección y sanción a que haya lugar. &nbsp;</span></p>
      <p style="text-align:justify;line-height:normal;background:white;border:none;"><span style="font-size:12px;color:#44546A;">En este sentido, se específica que el usuario, por el hecho de ingresar al portal, se obliga a abstenerse de:</span></p>
      <p style="margin-bottom:.0001pt;text-align:justify;line-height:normal;border:none;"><span style="font-size:12px;color:#44546A;">4.1 Utilizar el contenido con fines o efectos contrarios a las leyes de Colombia, del lugar donde reside el usuario o desde el que accede a <strong>Educonexiones.</strong> &nbsp;</span></p>
      <p style="margin-bottom:.0001pt;text-align:justify;line-height:normal;border:none;"><span style="font-size:12px;color:#44546A;">4.2 Reproducir, copiar, imprimir, distribuir, editar, modificar y/o comercializar total o parcialmente el contenido dispuesto en <strong>Educonexiones.</strong></span></p>
      <p style="margin-bottom:.0001pt;text-align:justify;line-height:normal;border:none;"><span style="font-size:12px;color:#44546A;">4.3 Suprimir, eludir o manipular los derechos de autor: marcas y registros presentes en los textos, imágenes, audios, videos y demás contenido del portal.</span></p>
      <p style="margin-bottom:.0001pt;text-align:justify;line-height:normal;border:none;"><span style="font-size:12px;color:#44546A;">4.4 Publicar y enviar cualquier material y/o contenido obsceno, pornográfico, ofensivo, profano, difamatorio, etc; así como amenazas y/o acciones que violen ley.&nbsp;</span></p>
      <p style="margin-bottom:.0001pt;text-align:justify;line-height:normal;border:none;"><span style="font-size:12px;color:#44546A;">4.5 Enviar cualquier tipo de propaganda, avisos comerciales, políticos, religiosos o de cualquier otra naturaleza.</span></p>
      <p style="margin-bottom:.0001pt;text-align:justify;line-height:normal;border:none;"><span style="font-size:12px;color:#44546A;">4.6 Guardar los contenidos de <strong>Educonexiones</strong> en cualquier medio o dispositivo electrónico.&nbsp;</span></p>
      <p style="margin-bottom:.0001pt;text-align:justify;line-height:normal;border:none;"><span style="font-size:12px;color:#44546A;">4.7 Usar el portal y sus contenidos para fines distintos a los permitidos por las disposiciones legales aplicables.</span></p>
      <p style="margin-bottom:.0001pt;text-align:justify;line-height:normal;border:none;"><span style="font-size:12px;color:#44546A;">&nbsp;</span></p>
      <ol style="list-style-type: undefined;margin-left:0cmundefined;">
         <li><strong><span style="font-size:12px;color:#44546A;">Uso de la plataforma por adultos y menores de edad &nbsp;</span></strong></li>
      </ol>
      <p style="text-align:justify;line-height:normal;background:white;border:none;"><span style="font-size:12px;color:#44546A;">Teniendo presente que los contenidos dispuestos en el portal son de carácter educativo y que muchos de estos están dirigidos a menores de edad, el acceso de estos se encuentra supeditado al registro en el portal de un adulto o entidad responsable (familiar, tutor, institución educativa, docente) que será el directo encargado de supervisar y garantizar el correcto uso del portal por parte de niños, niñas o jóven. En conformidad con esto, el usuario y adulto responsable del menor, exime a <strong>Estratégica Comunicaciones</strong> de cualquier responsabilidad asociada con el acceso al portal, uso de los contenidos dispuestos en este o incumplimiento de las leyes vigentes en Colombia. &nbsp;</span></p>
      <p style="text-align:justify;line-height:normal;background:white;border:none;"><span style="font-size:12px;color:#44546A;">De igual manera se advierte al usuario, que <strong>Estratégica Comunicaciones&nbsp;</strong>no se hará responsable por daños o afectaciones en los dispositivos tecnológicos usados mientras esté en el portar <strong>Educonexiones</strong>. Dado que esta acción se desarrolla bajo la decisión y riesgo del usuario, se entiende que es este quien debe asumir cualquier daño a su computadora, equipo, sistema o datos contenidos en los mismos.&nbsp;</span></p>
      <p style="text-align:justify;line-height:normal;background:white;border:none;"><span style="font-size:12px;color:#44546A;">Es importante tener en cuenta que tanto la versión gratuita como la subscripción que requiere pago, tienen una vigencia de uso que depende de la extensión de los contenidos y que se especifica al momento de realizar la compra. Si el usuario no hace uso del portar, su servicios y contenidos en el tiempo estipulado, una vez vencidos los términos de la compra, no podrá acceder a estos.&nbsp;</span></p>
      <p style="text-align:justify;line-height:normal;background:white;border:none;"><span style="font-size:12px;color:#44546A;">Para hacer seguimiento al acceso y tiempo de vigencia de los contenidos, el usuario puede acceder a su sesión, allí encontrará un reporte detallado y un calendario que le permite contabilizar los días de vigencia.&nbsp;</span></p>
      <ol style="list-style-type: undefined;margin-left:0cmundefined;">
         <li><strong><span style="font-size:12px;color:#44546A;">Hipervínculos a sitios de terceros</span></strong></li>
      </ol>
      <p style="text-align:justify;line-height:normal;background:white;border:none;"><span style="font-size:12px;color:#44546A;">En la sección “Ideas para + conexiones”, se sugieren sitios web de terceros en los que el usuario puede ampliar información sobre determinados contenidos educativos, pero queda a discreción de este acceder o no. Por lo anterior, es el usuario quien asumirá la responsabilidad y adoptará las medidas de seguridad que considere necesarias para el acceso y exploración de contenidos. &nbsp;&nbsp;</span></p>
      <p style="text-align:justify;line-height:normal;background:white;border:none;"><span style="font-size:12px;color:#44546A;">Al respecto, se aclara que <strong>Estratégica Comunicaciones</strong> no tiene vínculos con ninguno de los sitios web referenciados: no respalda, patrocina, valida o tiene injerencia alguna en la publicación o eliminación de contenidos y salva responsabilidades frente a esto y su vigencia en la web.&nbsp;</span></p>
      <p style="text-align:justify;line-height:normal;background:white;border:none;"><span style="font-size:12px;color:#44546A;">Pese a lo anteriormente expuesto, el usuario que acceda a los sitios referenciados, se obliga bajo los mismos términos dispuestos en el numeral 4 de este documento, pues los contenidos de terceros también están protegidos por las leyes de derechos de autor y propiedad intelectual. &nbsp;</span></p>
      <ol start="7" style="margin-top:0cm;" type="1">
         <li style="color:#44546A;text-align:justify;line-height:normal;background:white;border:none;"><strong><span style="font-size:12px;">Derechos de autor y propiedad intelectual</span></strong></li>
      </ol>
      <p style="text-align:justify;line-height:normal;background:white;border:none;"><span style="font-size:12px;color:#44546A;">Tanto el portal como los contenidos que hacen parte de este (imágenes, textos, audios, videos etc.), exceptuando los que se referencian en la sección “Ideas para + conexiones”, son propiedad de <strong>Estratégica Comunicaciones,</strong> y se encuentran protegidos por las leyes de propiedad intelectual y derechos de autor, razón por la que no podrán ser objeto de explotación, publicación, reproducción, distribución, modificación o cesión, por otros. En este sentido, exceptuando aquello que esté autorizado de manera explícita por <strong>Estratégica Comunicaciones</strong>, el acceso al portal no otorga a los usuarios derecho, ni titularidad alguna sobre los contenidos que alberga en el sitio.</span></p>
      <p style="text-align:justify;line-height:normal;background:white;border:none;"><span style="font-size:12px;color:#44546A;">Al aceptar los términos y condiciones aquí dispuestos, usted como usuario del portal, reconoce que <strong>Estratégica Comunicaciones</strong> posee todos y cada uno de los derechos patrimoniales de todas y cada una de los contenidos del portal. &nbsp;</span></p>
      <ol style="list-style-type: undefined;margin-left:0cmundefined;">
         <li><strong><span style="font-size:12px;color:#44546A;">Violación de derechos de autor y propiedad intelectual</span></strong><span style="font-size:12px;color:#44546A;">.&nbsp;</span></li>
      </ol>
      <p style="text-align:justify;line-height:normal;background:white;border:none;"><span style="font-size:12px;color:#44546A;">Dado el caso en que un usuario o tercero tenga razones para considerar que algún contenido alojado en este portal es de su propiedad y que se están violando sus derechos sobre este, debe notificar formalmente a <strong>Estratégica Comunicaciones</strong> y enviar la siguiente información:&nbsp;</span></p>
      <ol class="decimal_type" style="list-style-type: undefined;">
         <li><span style="font-size:12px;color:#44546A;">Datos básicos de contacto: nombre completo, número de identificación, país, correo electrónico y teléfono.</span></li>
         <li><span style="font-size:12px;color:#44546A;">Indicación precisa del contenido presuntamente infringido y su ubicación en el portal.&nbsp;</span></li>
         <li><span style="font-size:12px;color:#44546A;">Pruebas de la autoría del contenido y presentación de los derechos de propiedad industrial y/o intelectual que posee de estos.&nbsp;</span></li>
         <li><span style="font-size:12px;color:#44546A;">Declaración firmada ante autoridades competencias en la que certifique que la información es veraz y que los contenidos en mención están siendo afectados por violación de derechos de propiedad intelectual y/o derechos de autor. &nbsp; &nbsp;</span></li>
      </ol>
      <p style="text-align:justify;line-height:normal;background:white;border:none;"><span style="font-size:12px;color:#44546A;">Dicha notificaciones deberán ser enviadas<em>&nbsp;</em>al correo electrónico ( pendiente) y &nbsp;en físico a la dirección: &nbsp; ------------------------- Bogotá D.C.&nbsp;</span></p>
      <ol style="list-style-type: undefined;margin-left:0cmundefined;">
         <li><strong><span style="font-size:12px;color:#44546A;">Alcance de los términos y condiciones de uso&nbsp;</span></strong></li>
      </ol>
      <p style="text-align:justify;line-height:normal;background:white;border:none;"><span style="font-size:12px;color:#44546A;">Se sobreentiende que el usuario al acceder al portal, acepta de manera irrevocable los términos y condiciones aquí dispuestos, y que en caso de requerir arbitrar algo de lo aquí expuesto, la jurisdicción para presentar los requerimientos legales está circunscrita a los espacios estipulados por la ley en la ciudad de Bogotá – Colombia, independientemente de su domicilio presente o futuro de quien presente el requerimiento.&nbsp;</span><span style="font-size:12px;font-family:Montserrat;color:#44546A;">&nbsp; &nbsp;</span></p>
      <p style="text-align:justify;"><span style="color:#44546A;">&nbsp;</span></p>
   </div>
</div>